### ISSUE TITLE
Hard Error: No such column IsSharedAlbum

### ISSUE THREAD

**Issue by Doug411** [gilesknap/gphotos-sync#495]
I am having 2 issues with gphotos-sync.  The first issue is that it doesnt pick up new photos added to shared albums.  I have to add parameter --rescan to force it to happen.

The second issue occured in my most recent run.   I received a hard error "no such column: IsSharedAlbum".    My compose file and error log are included below.

```
services:
  gphotos-sync:
    container_name: gphotos-sync
    volumes:
      - ./:/config # BACKUP
      - ${FOLDER_FOR_MEDIA}/photos:/storage # SKIP_BACKUP
    #ports:
    #  - 8080:8080
    stdin_open: true
    # tty: true
    image: ghcr.io/gilesknap/gphotos-sync
    environment:
      TZ: ${TIMEZONE}
    command: --progress --db-path=/config --omit-album-date
      --rescan --logfile=/config/gphotos.log --albums-path=/storage/Albums-Doug
      --photos-path=/storage/Photos-Doug /storage
```

Subset of error log (end of file)

```
gphotos-sync  | 06-25 10:04:02 WARNING  Listed 16580 items ... 
gphotos-sync  | 06-25 10:04:02 WARNING  Listed 16590 items ... 
gphotos-sync  | 06-25 10:04:02 WARNING  Listed 16600 items ... 
gphotos-sync  | 06-25 10:04:02 WARNING  Listed 16610 items ... 
gphotos-sync  | 06-25 10:04:02 WARNING  indexed 0 items 
gphotos-sync  | 06-25 10:04:02 WARNING  Downloading Photos ... 
gphotos-sync  | 06-25 10:04:02 WARNING  Downloaded 0 Items, Failed 0, Already Downloaded 25307 
gphotos-sync  | 06-25 10:04:02 WARNING  Indexing Shared (titled) Albums ... 
gphotos-sync  | 06-25 10:04:03 WARNING  Done. 
gphotos-sync  | 06-25 10:04:03 ERROR    
gphotos-sync  | Process failed. 
gphotos-sync  | Traceback (most recent call last):
gphotos-sync  |   File "/root/.local/lib/python3.12/site-packages/gphotos_sync/__main__.py", line 553, in main
gphotos-sync  |     self.start(args)
gphotos-sync  |   File "/root/.local/lib/python3.12/site-packages/gphotos_sync/__main__.py", line 471, in start
gphotos-sync  |     self.do_sync(args)
gphotos-sync  |   File "/root/.local/lib/python3.12/site-packages/gphotos_sync/__main__.py", line 446, in do_sync
gphotos-sync  |     self.google_albums_sync.index_album_media()
gphotos-sync  |   File "/root/.local/lib/python3.12/site-packages/gphotos_sync/GoogleAlbumsSync.py", line 160, in index_album_media
gphotos-sync  |     self.index_albums_type(
gphotos-sync  |   File "/root/.local/lib/python3.12/site-packages/gphotos_sync/GoogleAlbumsSync.py", line 199, in index_albums_type
gphotos-sync  |     indexed_album = self._db.get_album(album_id=album.id)
gphotos-sync  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gphotos-sync  |   File "/root/.local/lib/python3.12/site-packages/gphotos_sync/LocalData.py", line 318, in get_album
gphotos-sync  |     self.cur.execute(query, (album_id,))
gphotos-sync  | sqlite3.OperationalError: no such column: IsSharedAlbum
```
