### ISSUE TITLE
Problem with symlinks under Win 10

### ISSUE THREAD

**Issue by mr-dosmo** [gilesknap/gphotos-sync#90]
Downloading of all photos went well. Then gphotos-sync created one album folder and one symlink. It exited with:
`NotImplementedError: utime: follow_symlinks unavailable on this platform`

Versions are:
Python 3.7.4
gphotos-sync 2.9
Windows 10 1803

As I prefer hardlinks I would be happy to see `--do-hardlinks` in the next version of gphotos-snc as mentioned in #79.

**Comment by gilesknap** [comment]
WIndows in its wisdom does not enable softlinks by default. See here
https://community.perforce.com/s/article/3472 for how to switch it on.

--do-hardlinks is implemented in the master branch if you would like to try
it. I will release it soonish. However, I have no idea what windows will do
with hardlinks so please let me know how you get on.

**Comment by mr-dosmo** [comment]
Thanks for your fast answer.

Symlinks are enabled, of course.

`mklink test.txt LICENSE.txt`
results in
`symbolic link created for test.txt <<===>> LICENSE.txt`

As I wrote gphotos-sync creates one symlink in one album folder. Then it exits with: 


Process failed.
Traceback (most recent call last):
  File "c:\users\me\.virtualenvs\python-hsrnnotq\lib\site-packages\gphotos\Main.py", line 329, in main
    self.start(args)
  File "c:\users\me\.virtualenvs\python-hsrnnotq\lib\site-packages\gphotos\Main.py", line 301, in start
    self.do_sync(args)
  File "c:\users\me\.virtualenvs\python-hsrnnotq\lib\site-packages\gphotos\Main.py", line 287, in do_sync
    self.google_albums_sync.create_album_content_links()
  File "c:\users\me\.virtualenvs\python-hsrnnotq\lib\site-packages\gphotos\GoogleAlbumsSync.py", line 230, in create_album_content_links
    follow_symlinks=False)
NotImplementedError: utime: follow_symlinks unavailable on this platform

**Comment by gilesknap** [comment]
OK sorry for not picking up on that. I have added setting the photo date on
the links. It looks like this is not supported on Windows.

I will fix and also see if I can add Windows to the Continuous Integration
tests.

**Comment by gilesknap** [comment]
Hi, I've made a fix but not yet added Windows to the test matrix (that is a bit more work).

Please, can you try the latest in the master branch for me?  Thanks.

**Comment by mr-dosmo** [comment]
It is working.

Thank you very much for the great tool.

**Comment by gilesknap** [comment]
Thanks for the update.

Leaving this issue open as a reminder to add WIndows to the CI test matrix.

**Comment by gilesknap** [comment]
I got this on Travis:

The language 'python' is currently unsupported on the Windows Build Environment.
Let us know if you'd like to see it: https://travis-ci.community/c/environments/windows. Thanks for understanding!

**Comment by gilesknap** [comment]
OK, it might not be directly supported but this worked for me and added OSX too (still working on getting all tests to pass)

```
language: python
matrix:
  include:
    - os: osx
      language: sh
      python: "3.7"
      # Perform the manual steps on osx to install python3 and activate venv
      before_install:
        - brew update
        - brew upgrade python3
        - python3 -m pip install virtualenv
        - virtualenv .venv -p python3
        - source .venv/bin/activate
        - python -m pip install mock
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python -m pip install mock
    - python: 3.6.7
      dist: xenial
      sudo: true
    - python: 3.7.2
      dist: xenial
      sudo: true
```
